
## [Call Expressions](https://www.inferentialthinking.com/chapters/03/3/Calls) (Inferential Thinking - 3.3)

Call expressions invoke functions, which are named operations. The name of the function appears first, followed by expressions in parentheses.

### Anatomy of a Call Expression
<img src = 'anatomy_call.jpg' width = 400/>
"Call f on the result of adding x + y and the return value of calling g on z"

In [1]:
abs(-12)

12

**round** is a function takes in 2 arguments:
1. An expression to calculate
2. The number of decimal places desired in the return value

If you only give the function 1 argument, **round** will return an integer.

In [2]:
round(5 - 1.3)

4

In [3]:
round(5 - 1.342, 2)

3.66

In [4]:
round(5-1.342, 3)

3.658

In [5]:
max(2, 2 + 3, 4)

5

In this last example, the max function is called on three arguments: 2, 5, and 4. The value of each expression within parentheses is passed to the function, and the function returns the final value of the full call expression. The max function can take any number of arguments and returns the maximum.

A few functions are available by default, such as abs and round, but most functions that are built into the Python language are stored in a **collection of functions** called a **module**. An **import** statement is used to provide access to a module, such as math or operator.

In [6]:
import math
import operator
math.sqrt(operator.add(4, 5))

3.0

Above is equivalent to the following:

In [ ]:
(4 + 5) ** 0.5

**Operators** and **call** expressions can be used together in an expression. The percent difference between two values is used to compare values for which neither one is obviously initial or changed. For example, in 2014 Florida farms produced 2.72 billion eggs while Iowa farms produced 16.25 billion eggs (http://quickstats.nass.usda.gov/). The percent difference is 100 times the absolute value of the difference between the values, divided by their average. In this case, the difference is larger than the average, and so the percent difference is greater than 100.

In [7]:
florida = 2.72
iowa = 16.25
100*abs(florida-iowa)/((florida+iowa)/2)

142.6462836056932

Learning how different functions behave is an important part of learning a programming language. A Jupyter notebook can assist in remembering the names and effects of various functions. When writing code, press **tab** after typing the beginning of a name to bring up a list of ways to complete that name. For example, press **tab** after the word **math**. 
To see all of the functions available in the math module. Typing will narrow down the list of options. To learn more about a function, place a ? after its name. For example, typing math.log? will bring up a description of the log function in the math module.

In [9]:
math.log?

The square brackets **[ ]** in the example call indicate that an argument is optional. That is, log can be called with either one or two arguments.

In [10]:
math.log(16, 2)

4.0

In [11]:
math.log(16)/math.log(2)

4.0

The list of [Python’s built-in functions](https://docs.python.org/3/library/functions.html) is quite long and includes many functions that are not needed in data science applications. The list of [mathematical functions in the math module](https://docs.python.org/3/library/math.html) is similarly long. This text will introduce the most important functions in context, rather than expecting the reader to memorize or understand these lists.


## [String](https://www.inferentialthinking.com/chapters/04/2/Strings) (Inferential Thinking - 4.2)

* A string value is a snippet of text of any length
    * 'a'
    * 'word'
    * "there can be 2 sentences. Here's the second!"
* String that contain numbers can be converted to numbers
    * int('12')
    * float('1.2')
* Any value can be converted to a string
    * str(5)

Much of the world’s data is text, and a piece of text represented in a computer is called a **string**. Since text can include numbers or truth values (True, False), a string can also describe them.

The meaning of an expression depends both upon its structure and the types of values that are being combined. For example, adding 2 strings together produces another string. This expression is still an addition expression, but it is combining a different type of value.

In [12]:
"data" + "science"

'datascience'

In [13]:
"data" + " " + "science"

'data science'

Single and double quotes can both be used to create strings: 'hi' and "hi" are the same. Double quotes are preferred because they allow you to include apostrophes inside of strings.

In [14]:
"This won't work with a single-quoted string!"

"This won't work with a single-quoted string!"

### A Note on Functions / Methods
* Functions are called by themselves
    * abs(-2)
    * int('42')
* Methods are tied to a particular type
    * 'hello'.count(2)
    * 'Sam is kinda cool'.replace('kinda', 'very')
    * math.pow(2, 5)

## Arrays
An array contains a sequence of values
* All elements of an array should have the same type
* Arithmetic is applied to each element individually
* When 2 arrays with the same length are added to each other, corresponding elements are added (i.e. [1, 2, 3] + [2, 5, 7] = [3, 7, 10])

### Demo - [Sequence](https://www.inferentialthinking.com/chapters/05/Sequences) (Inferential Thinking - 5)
Values can be grouped together into collections so that programmers can organize those values and refer to all of them with a single name. By grouping values together, we can write code that performs a computation on many pieces of data at once.

The function **make_array** creates an array containing several values. Note that you need to import the **datascience** library to use the function.

Below, we store 4 different temperatures into an array called **highs**. These 4 temperatures are the [estimated average daily high temperatures](http://berkeleyearth.lbl.gov/regions/global-land) over the land on Earth (in Celsius) for the decades surrounding 1850, 1900, 1950, and 2000, respectively, expressed as deviations from the average absolute high temperature between 1951 and 1980, which was 14.48 degrees.

In [4]:
from datascience import *
baseline_high = 14.48
highs = make_array(
    baseline_high - 0.880, #1850
    baseline_high - 0.093, #1900
    baseline_high + 0.105, #1950
    baseline_high + 0.684) #2000
highs

array([13.6  , 14.387, 14.585, 15.164])

Collections allow us to pass multiple values into a function using a single name. For instance, the sum function computes the sum of all values in a collection, and the len function computes its length. (That’s the number of values we put in it.) Using them together, we can compute the **average** of a collection.

In [5]:
average = sum(highs)/len(highs)
average

14.434000000000001

Arrays can be used in arithmetic expressions to compute over their contents. When an array is combined with a single number, that number is combined to each element of the array. Therefore, we can convert all of these temperatures to Fahrenheit by writing the familiar conversion formula.

In [7]:
Fahrenheit = (9/5) * highs + 32
Fahrenheit

array([56.48  , 57.8966, 58.253 , 59.2952])

Arrays also have **methods**, which are functions that operate on the array values. Here's an example of method **sizee** that calculates the length of an array.

In [ ]:
highs.size

Here we call a function with no argument to perform the **sum** of the elements in an array.

In [10]:
highs.sum()

57.736000000000004

The **mean** is the average value: the sum divided by the length.

In [11]:
highs.mean()

14.434000000000001

### Functions on Arrays
The **numpy** package, abbreviated np in programs, provides convenient and powerful functions for creating and manipulating arrays.

In [12]:
import numpy as np

For example, the **diff** function computes the difference between each adjacent pair of elements in an array. The first element of the diff is the second element minus the first.

In [13]:
np.diff(highs)

array([0.787, 0.198, 0.579])

The [full Numpy reference](http://docs.scipy.org/doc/numpy/reference/) lists all the functions, but onaly a few of them are used commonly for data processing applications. These are grouped into different packages within np. Learning this vocabulary is an important part of learning the Python language, so refer back to this list often as you work through examples and problems.

**However, you don’t need to memorize these. Use this as a reference.**

Each of these functions takes an array as an argument and **returns a single value**.

|Function|Description| 
|  ---  |  ---  |
|  np.prod  | Multiply all elements |
|  np.sum  | Sum all elements |
|  np.all  | Check if **all** elements are True (non-zero numbers are True) |
|  np.all  | Check if **any** elements are True (non-zero numbers are True) |
|  np.count_nonzero  | Count the number of non-zero elements |

Each of these functions takes an array as an argument and **returns another array**.

|Function|Description| 
|  ---  |  ---  |
|  np.diff  |Difference between adjacent elements |
|  np.round  | Round each number to the nearest integer (whole number) |
|  np.cumprod  | A cumulative product (For each element, multiply all elements so far |
|  np.cumsum  | A cumulative sum (For each element, add all elements so far) |
|  np.exp  | Exponentiate each element |
|  np.log  | Return natural logarithm of each element |
|  np.sqrt  | Return the square root of each element |
|  np.sort  | Sort elements |

## Ranges
A range is an array of numbers in increasing or decreasing order, each separated by a regular interval.
* np.arange(end):
    * An array of increasing integers from 0 up to **end**
* np.arange(start, end):
    * An array of increasing integers from **start** to **end**
* np.arange(start, end, step):
    * A range with **step** (an amount of interval) between consecutive values
    
Range always includes **start** but **excludes end**.