Use Broadcasting to create a 4x4 ndarray that has its first column full of `1`s, its 2nd column full of `2`s, 
its third column full of `3`s, etc.

In [1]:
import numpy as np

In [5]:
X = np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
Y = np.array([0, 1, 2, 3])

In [8]:
X + Y

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [10]:
# One line solution 
np.ones((4, 4)) + np.arange(0, 4)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [11]:
# Alternative solution
np.ones((4, 4)) * np.arange(1, 5)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])