In [1]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

# Call Expressions
Yesterday we mostly covered arithmetic expressions (i.e. `1 + 1` , `2 * 3`). Call expressions allow us to work with Python functions, which will allow us to do more than just addition, subtraction and other basic operations. For example, below is a function that takes in an input and returns the absolute value of the input. 

In [2]:
abs(-12)

12

1. `abs` is the function name
    * Think of function as the verb
2. `-12` is the input value, or `argument`
    * Think of the input as a noun

So think of it as doing an activity to something.

In this class, you might hear the following words used interchangibly:
1. The word `argument ` and `input argument`
2. The word `function call` and `call expression`

We can also use an expression as an argument. The following is an example of using the `round` function to round up a decimal number.

In [3]:
round(5 - 1.3333)

4

`round` can take a second argument, which is the number of decimal places desired. The default value is 0, which means if no second argument is given, then Python will treat is it as 0.

In [4]:
round (5 - 1.3333, 2)

3.67

Some functions can take multiple arguments, such as `max` that returns the greatest value among the arguments given.

In [5]:
max(2, 3 + 4, 8)

8

If we give too much argument to a function, it will give an error!

In [6]:
abs(-21, 4)

TypeError: abs() takes exactly one argument (2 given)

Functions such as `abs`, `max` and `round` are readily available. However, most math functions are not available right away; we need to import it from a package called `math`. The `math` package is a package that contains useful functions for computations. 

If we want to use a function from a package, we write the name of the package, combined by `.` dot, then the package name. Below is an example of using `math`'s square root function

In [ ]:
import math
math.sqrt(9)

We can see the functions `math` package has by typing `math.` and then pressing the `tab` button on a code cell.

In [ ]:
# press tab right after the dot
math.

In [ ]:
# Here is an example of taking the sin of pi/2
math.sin(math.pi/2)

If we forgot what a function does, we can type a function and type `?` question mark WITHOUT TYPING THE PARENTHESES.

In [ ]:
math.log?

<img src = 'log.jpg' width = 400\>
When we look up how the `log` function works, we'll see the following. This means the `log` function can take either one or 2 arguments. The first argument is required, while the second optional argument serves as the base of the logarithm. If you don't give any argument, it will give an error

In [ ]:
math.log()

In [ ]:
math.log(1000)

Recall the definition of logarithm. This means `e` to the power of `6.907755278982137` would result in 1000. If we try to calculate it manually,

In [ ]:
math.pow(math.e, 6.907755278982137)

Above, Python does not give exactly 1000 due to precision limitation, but it is close enough!

In [ ]:
abs?

# Recap: Anatomy of Call Expression
<img src = 'anatomy_call.jpg' width = 400\>

1. `f` is the function name
2. `x + y` is a call expression and on the same time the first argument
3. `g (z)` is another call expression and on the same time the second argument

We can word the whole thing as:
"Call `f` on the result of adding `x + y` and the return value of calling `g` on `z`

## Discussion Question

In [ ]:
import math
x = 3
y = -2.0

Which of these examples will result in an error?

In [ ]:
# Error! Too many arguments!
abs(x, y)

In [ ]:
math.pow(x, abs(y))

In [ ]:
round(x, max(abs(y ** 2)))
# Error because the max function needs to take an iterable or more than one argument, while here we only give one

In [ ]:
math.pow(x, math.pow(y, x))

# String
So far we have been covering about numbers. This time, we will cover text!

## Text and Strings
Texts in Python are represented as `string`. A `string` value is a snippet of text of any length. Examples:

In [ ]:
'a'

In [ ]:
'word'

In [ ]:
"there can be 2 sentences. Here's the second!"

A `string` can be made with either single quotes `'` or double quotes `"`. Make sure to close the quotes whenever you start it.

Strings that contain numbers can be converted to numbers using the function `int` or `float`.

In [ ]:
int('12')

In [ ]:
float('1.2')

Any value can be converted to a string.

In [ ]:
str(5)

## Demo
If we add multiple strings together, it will be combined to a string.

In [ ]:
"data" + "8" + " is cool"

Be careful with single quotes! Below is an example where you get error because of single quotes issue.

In [ ]:
'It's an error!'

If we create the string above with double string, there would be no problem.

In [ ]:
"It's an error!"

Python has an escape character `\` that treats the character after it as a string.

In [ ]:
'It\'s an error!'

## Discussion Question

In [ ]:
x = 3
y = '4'
z = '5.6'

What's the source of error in each example?

In [ ]:
# We can't add together integer and string!
x + y

In [ ]:
# The result of y + z is '45.6', which is not a vaild integer. You can't convert this to int
x + int(y + z)

In [ ]:
# You can't add a string with an int
str(x) + int(y)

In [ ]:
str(x, y) + z

## Back to Demo
Python has a function `type` that tells us the type of value we passed as the input.

In [ ]:
type(3)

In [ ]:
type(3.0)

In [ ]:
type('3.0')

What would happen if we do the following?

In [ ]:
# It works just fine!
int('3' + '4') + 5

Python also has `boolean` values, which will be covered later in the course.

In [ ]:
3 > 2

In [ ]:
2 > 3

## A Note on Functions / Methods
A function call is different from a method call.

Functions are called by themselves. Below examples are function calls.

In [ ]:
abs(-2)

In [ ]:
int('42')

Methods, on the other hand, are tied to a particular type.

In [ ]:
'hello'.count('l')

Above, the `count` method is a `string` method that counts the occurrence of a certain input.

In [ ]:
'I am kinda cool'.replace('kinda', 'very') #Another example of a string method

In [ ]:
math.pow(2, 5) #This is an example of using the math package's method

# Arrays
So far we have been working with individual numbers. Now let's say we're trying to keep track of how many friends the course staff has.

In [ ]:
nanxi = 4
arvind = 5
katherine = 2
emma = 10
sam = 0

Now let's say the course staffs meet each other. This means each course staff's number of friends would increase by 4.

In [ ]:
nanxi = nanxi + 4
arvind = arvind + 4
katherine = katherine + 4
emma = emma + 4
sam = sam + 4

In [ ]:
katherine

The course staff's friends increased indeed! However, the code above involved unnecessary repetition. There is a better, more efficient way to do the same thing: using `array`. The function `make_array` creates an array, and we will use this to keep track of the number of friends each person has. 

Note that we need to import `datascience` package to be able to use `make_array`.

In [ ]:
from datascience import *

In [ ]:
friendship = make_array(4, 5, 2, 10, 0)
friendship

We can add each number in the array `friendship` by 4 by simply adding 4.

In [ ]:
friendship + 4

## Recap: Arrays
An array contains a sequence of values
* All elements of an array should have the same type
    * In example of course staff's friends, all the values need to be integers
* Arithmetic is applied to each element individually
    * When we add 4 to `friendship`, 4 is added to each element of `friendship`
* When 2 arrays of the same length are added with each other, corresponding elements are added as a result

Here we will analyze temperature change of the earth data taken from [Berkeley Earth](http://berkeleyearth.lbl.gov/regions/global-land).
<img src = 'mean_temp.jpg' width = 500\>
We choose the option `Data Table` to obtain the [data](http://berkeleyearth.lbl.gov/auto/Regional/TMAX/Text/global-land-TMAX-Trend.txt).

<img src = '30_year.jpg' width = 600\>
Above, Berkeley measured the global average temperature over the course of 30 years. They measured the temperature of the years in relation to that. From the measurement, they found that the average temperature is 14.48 $\pm$ 0.06.

Now there's something that's called `baseline high`, and we'll set it as the average temperature. Let's say we want to know the temperature at 1850, 1900, 1950 and 2000.

For year 1850, we'll pick the -0.880
<img src = '1850.jpg' width = 700\>
For year 1900, -0.093
<img src = '1900.jpg' width = 700\>
For year 1950, 0.105
<img src = '1950.jpg' width = 700\>
And finally for year 2000, 0.684
<img src = '2000.jpg' width = 700\>

In [8]:
baseline_high = 14.48
highs = make_array(
    baseline_high - 0.880, #Year 1850
    baseline_high - 0.093, #Year 1900
    baseline_high + 0.105, #Year 1950
    baseline_high + 0.684  #Year 2000
)
highs

array([13.6  , 14.387, 14.585, 15.164])

We can grab the first element, which is the temperature at 1850, by the following,

In [ ]:
highs.item(0)

But in reality, we want to work with all the elements at once. For example, if we want to convert all the temperatures from Celsius to Fahrenheit, we can do the following,

In [ ]:
(9 / 5) * highs + 32

We can find out the length of an array using `len`,

In [ ]:
len(highs)

We can also calculate the `sum` of the average temperatures,

In [ ]:
sum(highs)

We can take the `mean` with 2 different ways,

In [ ]:
# Way 1
highs.sum() / len(highs)

In [ ]:
# Way 2
highs.mean()

The `mean` method above only works for an array! You can't use `mean` method on other data types (i.e. string or integer).

Earlier, we worked with the max temperature or the `baseline high`. This time, we will work with the low temperatures.

In [9]:
baseline_low = 3.00
lows = make_array(
    baseline_low - 0.872,
    baseline_low - 0.629,
    baseline_low - 0.126,
    baseline_low + 0.728,
)
lows

array([2.128, 2.371, 2.874, 3.728])

We can calculate temperature difference between `highs` and `lows` for each year just by using subtraction,

In [ ]:
highs - lows

And we can do the same thing as above in Fahrenheit!

In [10]:
(9/5 * highs + 32) - (9/5 * lows + 32)

array([20.6496, 21.6288, 21.0798, 20.5848])

From the calculation above, it appears that the differences etween `highs` and `lows` for every 50 years are about the same. We can check if this is true by looking at the world temperature maps below,


If we compare the 2 maps, notice the following:
1. For regions near equitorial line:
    * There aren't significant difference in temperature between daytime and night
2. For some other regions (e.g. Australia):
    * The daytime temperature is significantly warmer than the night temperature

# Ranges
Another way of constructing an array without typing every single element is by creating a `range`. A `range` is an array of consecutive numbers. This is mostly done through the method `arange` within `numpy` package.

#### `np.arange(end)`
Creates an array of increasing integers from 0 up to (but not including) `end`

In [11]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### `np.arange(start, end)`
Creates an array of increasing integers from `start` up to (not including) `end`

In [12]:
np.arange(2, 7)

array([2, 3, 4, 5, 6])

#### `np.arange(start, end, step)`
Creates a `range` with `step` between consecutive values

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

The `range` always includes `start` but always excludes `end`.

## Discussion Question

In [14]:
x = make_array(2, 3, 4)
y = np.arange(2, 3, 4)
z = np.arange(3)

Which lines would cause an error?

In [16]:
# np.arange(2, 3, 4) is just 2. So this is basically array [2, 3, 4] + 2
x + y

array([4, 5, 6])

In [17]:
x + z

array([2, 4, 6])

In [18]:
x.item(0) + y.item(0)

4

In [19]:
# This will give an error! y only contains 2, so there's only 1 element in y!
x.item(1) + y.item(1)

IndexError: index 1 is out of bounds for axis 0 with size 1